global:
  scrape_interval: 15s
  external_labels:
    monitor: 'fraud-dbms'

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8080']

